### ISSUE TITLE
cannot reproduce the results in README

### ISSUE THREAD

**Issue by jkd2021** [SysCV/pcan#23]
![bdd_results](https://user-images.githubusercontent.com/95178395/184710977-41440b89-bf29-4a5f-97b4-ad54cabf2dfb.png)
like what is showed in this image, after running the tools/test.py in your code, with these in README given config and pretrained weights, I cannot reproduce the results of the "Scores-val" in README. Did you also get this result on seg_track_val_cocoformat.json (which can be downloaded in the bdd100k website)? I am really confused about that.

**Comment by lkeab** [comment]
The Readme result is obtained after further converting the results from coco format to BDD format on BDD online evaluation benchmark. Due to the annotation format change like from polygon to bitmasks, the small [result difference](https://github.com/SysCV/pcan/blob/main/docs/GET_STARTED.md#note-on-bdd-segmentation-tracking-split) are normal. Please follow the instruction [here](https://github.com/SysCV/pcan/blob/main/docs/GET_STARTED.md#conversion-to-the-bdd100kscalabel-format-and-evalution).

**Comment by jkd2021** [comment]
But why is the MOTA of pedestrian varying so much from the statistics in the repository? (Just curious to auch a big difference)

**Comment by lkeab** [comment]
Not sure about it as the online benchmark is constructed by bdd100k team. My guessing reason is that changing from polygons to bitmask has most influence on pedestrian, or they correct some wrong annotations for pedestrian. You can upload you results to evaluation server to check it.

**Comment by jkd2021** [comment]
Alright, got it, thanks a lot to your explanation.

**Comment by jkd2021** [comment]
Alright, got it, thanks a lot for your explanation.

**Comment by dccdcc7** [comment]
hello, have you encoutered
ModuleNotFoundError: No module named 'mmcv._ext'
when you performed steps mentioned in GET_STARTED.md?
thank u
